### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by jeffren716** [jeffren716/Stitch#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by jeffren716** [comment]
Modal implementation is hacky

**Comment by AAlfarho** [comment]
Good job, just a couple of things 

+ Errors on your modals are not being reset after switching between them, or even after closing the modal.
+ There is a lot of horizontal space in your modal form, let's make use of it.
+ The form itself requires a bit of styling, the inputs are not aligned.
+ Whenever there is a modal, intuitive behavior is to close it hitting `esc`, let's add this to your modal.
+ Whenever a modal is opened, clean up the input fields, as the values are carried across when closing login and opening up sign up, or vice-versa.

**Comment by jeffren716** [comment]
added all fixes(esc functionality took a while) but this mvp should be finished
