### ISSUE TITLE
PA Review: Video

### ISSUE THREAD

**Issue by jeffren716** [jeffren716/Stitch#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by jeffren716** [comment]
fixed channels bug with adequate seeding

**Comment by AAlfarho** [comment]
Good Job Jef. I think my favorite stream was the one with Jonathan Blow coding.
One extra thing to consider is to set some padding on the user-header-info and resize the username and or title to make them pop a little bit more. Raise a new enhancement/style issue to address this. MVP completed.
