### ISSUE TITLE
PA Review: Search

### ISSUE THREAD

**Issue by jeffren716** [jeffren716/Stitch#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by jeffren716** [comment]
* search does not implement redux state, utilizes internal component state
* in order to close the dropdown menu, search query must be cleared from the search bar
* document event listener listens for click and clears the query

**Comment by AAlfarho** [comment]
Great job!
Search functionality is done.
A thing to consider is that for some reason sometimes the results come in, the images are not loaded, keep this in mind for future enhancements, maybe track this with an additional issue?
