### ISSUE TITLE
PA Review: Follows

### ISSUE THREAD

**Issue by jeffren716** [jeffren716/Stitch#6]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by jeffren716** [comment]
Follows have a unique structure of ids where in the state, the id is the user id so the follow id I have to pass to delete the follow must be different

**Comment by AAlfarho** [comment]
Incredible work with the new layout for both user info in their streams and in the follow nav bar.
The eye candy in the _follow_ navbar is subtle but it gives a new feel to the site.
Kudos on the attention to detail, especially when trying to follow a user and not being logged in.
The new seeding on the avatar is great!

MVP completed!
